"""mahasiswas table

Revision ID: 4900f252529b
Revises: 26b18a963e5d
Create Date: 2019-11-28 12:45:08.131929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4900f252529b'
down_revision = '26b18a963e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('nim', sa.String(length=9), nullable=True),
    sa.Column('senin_a', sa.String(length=3), nullable=True),
    sa.Column('senin_b', sa.String(length=3), nullable=True),
    sa.Column('senin_C', sa.String(length=3), nullable=True),
    sa.Column('senin_d', sa.String(length=3), nullable=True),
    sa.Column('selasa_a', sa.String(length=3), nullable=True),
    sa.Column('selasa_b', sa.String(length=3), nullable=True),
    sa.Column('selasa_C', sa.String(length=3), nullable=True),
    sa.Column('selasa_d', sa.String(length=3), nullable=True),
    sa.Column('rabu_a', sa.String(length=3), nullable=True),
    sa.Column('rabu_b', sa.String(length=3), nullable=True),
    sa.Column('rabu_C', sa.String(length=3), nullable=True),
    sa.Column('rabu_d', sa.String(length=3), nullable=True),
    sa.Column('kamis_a', sa.String(length=3), nullable=True),
    sa.Column('kamis_b', sa.String(length=3), nullable=True),
    sa.Column('kamis_C', sa.String(length=3), nullable=True),
    sa.Column('kamis_d', sa.String(length=3), nullable=True),
    sa.Column('jumat_a', sa.String(length=3), nullable=True),
    sa.Column('jumat_b', sa.String(length=3), nullable=True),
    sa.Column('jumat_C', sa.String(length=3), nullable=True),
    sa.Column('jumat_d', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswa_nim'), 'mahasiswa', ['nim'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mahasiswa_nim'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
