"""mahasiswa table

Revision ID: 4d78e1a785c3
Revises: 4900f252529b
Create Date: 2019-12-01 17:53:24.408455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d78e1a785c3'
down_revision = '4900f252529b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('jumat_e', sa.String(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('kamis_e', sa.String(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('rabu_e', sa.String(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('selasa_e', sa.String(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('senin_e', sa.String(length=3), nullable=True))
    op.drop_column('mahasiswa', 'kamis_C')
    op.drop_column('mahasiswa', 'jumat_C')
    op.drop_column('mahasiswa', 'rabu_C')
    op.drop_column('mahasiswa', 'selasa_C')
    op.drop_column('mahasiswa', 'senin_C')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('senin_C', sa.VARCHAR(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('selasa_C', sa.VARCHAR(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('rabu_C', sa.VARCHAR(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('jumat_C', sa.VARCHAR(length=3), nullable=True))
    op.add_column('mahasiswa', sa.Column('kamis_C', sa.VARCHAR(length=3), nullable=True))
    op.drop_column('mahasiswa', 'senin_e')
    op.drop_column('mahasiswa', 'selasa_e')
    op.drop_column('mahasiswa', 'rabu_e')
    op.drop_column('mahasiswa', 'kamis_e')
    op.drop_column('mahasiswa', 'jumat_e')
    # ### end Alembic commands ###
